[package]
name = "benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.5"
ureq = "2"
json = "0.12"
json-parser = { path = "../" }

[[bench]]
name = "json_benchmark"
harness = false
path = "src/main.rs"